name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
    - name: Making sure 'npm run lint' does not change anything.
      run: |
        npm ci
        npm run lint
  test:
    runs-on: ${{ matrix.os }}
    needs:
      - test_lint
    strategy:
      matrix:
        node: [ '14', '12', '10' ]
        os: [ ubuntu-latest ]
    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - name: Tell if project is using npm or yarn
      id: step1
      uses: garronej/github_actions_toolkit@v2.2
      with:
        action_name: tell_if_project_uses_npm_or_yarn
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node }}
    - if: steps.step1.outputs.npm_or_yarn == 'npm'
      env:
        SSH_KEY_REGROOVE_MODELS: ${{secrets.SSH_KEY_REGROOVE_MODELS}}
      run: |
        mkdir $HOME/.ssh && echo "$SSH_KEY_REGROOVE_MODELS" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa && git submodule update --init --recursive
        npm ci
        npm run build
        npm test
  check_if_version_upgraded:
    name: Check if version upgrade
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version }}
    steps:
    - uses: garronej/github_actions_toolkit@v2.2
      id: step1
      with:
        action_name: is_package_json_version_upgraded
